#ifndef WIN32_WINSOCK2_INVALID_SOCKET_H
#define WIN32_WINSOCK2_INVALID_SOCKET_H


#if HAVE_INVALID_SOCKET || _WIN32
#define WANT_INVALID_SOCKET_WIN32	1
#else
#define WANT_INVALID_SOCKET_C99		1
#endif


#if WANT_INVALID_SOCKET_WIN32

#include <winsock2.h>	/* INVALID_SOCKET */

#endif /* WANT_INVALID_SOCKET_WIN32 */


#if WANT_INVALID_SOCKET_C99

#define INVALID_SOCKET	(-1)

#endif /* WANT_INVALID_SOCKET_C99 */


#endif /* WIN32_WINSOCK2_INVALID_SOCKET_H */
