#ifndef WIN32_WINSOCK2_WSAGETLASTERROR_H
#define WIN32_WINSOCK2_WSAGETLASTERROR_H


#if HAVE_WSAGETLASTERROR || _WIN32
#define WANT_WSAGETLASTERROR_WIN32	1
#else
#define WANT_WSAGETLASTERROR_C99	1
#endif


#if WANT_WSAGETLASTERROR_WIN32

#include <winsock2.h>	/* WSAGetLastError() */

#endif /* WANT_WSAGETLASTERROR_WIN32 */


#if WANT_WSAGETLASTERROR_C99

#include <errno.h>	/* errno */

#define WSAGetLastError()	errno

#endif /* WANT_WSAGETLASTERROR_C99 */


#endif /* WIN32_WINSOCK2_WSAGETLASTERROR_H */
