#ifndef NOSTD_SYS_PARAM_STRINGIFY_H
#define NOSTD_SYS_PARAM_STRINGIFY_H


#if !defined STRINGIFY
#define STRINGIFY_(s)	#s
#define STRINGIFY(s)	STRINGIFY_(s)
#endif


#endif /* !NOSTD_SYS_PARAM_STRINGIFY_H */
